
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>


using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;

namespace EspaceSyndic.ServiceReference {
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="BaseEntitie", Namespace="http://schemas.datacontract.org/2004/07/SyndicDocumentsData.Entities")]
    [Serializable()]
    [KnownType(typeof(ChildrenEntitie))]
    [KnownType(typeof(DocumentEntitie))]
    [KnownType(typeof(UserEntitie))]
    public partial class BaseEntitie : object, IExtensibleDataObject, INotifyPropertyChanged {
        
        [NonSerialized()]
        private ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private string GuidField;
        
        [OptionalField()]
        private DateTime audit_createdField;
        
        [OptionalField()]
        private Nullable<DateTime> audit_updatedField;
        
        [Browsable(false)]
        public ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [DataMember()]
        public DateTime audit_created {
            get {
                return this.audit_createdField;
            }
            set {
                if ((this.audit_createdField.Equals(value) != true)) {
                    this.audit_createdField = value;
                    this.RaisePropertyChanged("audit_created");
                }
            }
        }
        
        [DataMember()]
        public Nullable<DateTime> audit_updated {
            get {
                return this.audit_updatedField;
            }
            set {
                if ((this.audit_updatedField.Equals(value) != true)) {
                    this.audit_updatedField = value;
                    this.RaisePropertyChanged("audit_updated");
                }
            }
        }
        
        public event PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="ChildrenEntitie", Namespace="http://schemas.datacontract.org/2004/07/SyndicDocumentsData.Entities")]
    [Serializable()]
    public partial class ChildrenEntitie : BaseEntitie {
        
        [OptionalField()]
        private string Copro_idField;
        
        [OptionalField()]
        private string Immeuble_idField;
        
        [OptionalField()]
        private string User_idField;
        
        [DataMember()]
        public string Copro_id {
            get {
                return this.Copro_idField;
            }
            set {
                if ((ReferenceEquals(this.Copro_idField, value) != true)) {
                    this.Copro_idField = value;
                    this.RaisePropertyChanged("Copro_id");
                }
            }
        }
        
        [DataMember()]
        public string Immeuble_id {
            get {
                return this.Immeuble_idField;
            }
            set {
                if ((ReferenceEquals(this.Immeuble_idField, value) != true)) {
                    this.Immeuble_idField = value;
                    this.RaisePropertyChanged("Immeuble_id");
                }
            }
        }
        
        [DataMember()]
        public string User_id {
            get {
                return this.User_idField;
            }
            set {
                if ((ReferenceEquals(this.User_idField, value) != true)) {
                    this.User_idField = value;
                    this.RaisePropertyChanged("User_id");
                }
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="DocumentEntitie", Namespace="http://schemas.datacontract.org/2004/07/SyndicDocumentsData.Entities")]
    [Serializable()]
    public partial class DocumentEntitie : BaseEntitie {
        
        [OptionalField()]
        private string copro_idField;
        
        [OptionalField()]
        private string iconField;
        
        [OptionalField()]
        private string immeuble_idField;
        
        [OptionalField()]
        private string textField;
        
        [DataMember()]
        public string copro_id {
            get {
                return this.copro_idField;
            }
            set {
                if ((ReferenceEquals(this.copro_idField, value) != true)) {
                    this.copro_idField = value;
                    this.RaisePropertyChanged("copro_id");
                }
            }
        }
        
        [DataMember()]
        public string icon {
            get {
                return this.iconField;
            }
            set {
                if ((ReferenceEquals(this.iconField, value) != true)) {
                    this.iconField = value;
                    this.RaisePropertyChanged("icon");
                }
            }
        }
        
        [DataMember()]
        public string immeuble_id {
            get {
                return this.immeuble_idField;
            }
            set {
                if ((ReferenceEquals(this.immeuble_idField, value) != true)) {
                    this.immeuble_idField = value;
                    this.RaisePropertyChanged("immeuble_id");
                }
            }
        }
        
        [DataMember()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="UserEntitie", Namespace="http://schemas.datacontract.org/2004/07/SyndicDocumentsData.Entities")]
    [Serializable()]
    public partial class UserEntitie : BaseEntitie {
        
        [OptionalField()]
        private string CodeField;
        
        [OptionalField()]
        private string PasswordField;
        
        [DataMember()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [DataMember()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [OperationContract(Action="http://tempuri.org/IService/CreateUser", ReplyAction="http://tempuri.org/IService/CreateUserResponse")]
        string CreateUser(string Code, string Password);
        
        [OperationContract(Action="http://tempuri.org/IService/CreateUser", ReplyAction="http://tempuri.org/IService/CreateUserResponse")]
        Task<string> CreateUserAsync(string Code, string Password);
        
        [OperationContract(Action="http://tempuri.org/IService/UploadPartFile", ReplyAction="http://tempuri.org/IService/UploadPartFileResponse")]
        void UploadPartFile(string Guid, byte[] filePart);
        
        [OperationContract(Action="http://tempuri.org/IService/UploadPartFile", ReplyAction="http://tempuri.org/IService/UploadPartFileResponse")]
        Task UploadPartFileAsync(string Guid, byte[] filePart);
        
        [OperationContract(Action="http://tempuri.org/IService/CloseFile", ReplyAction="http://tempuri.org/IService/CloseFileResponse")]
        string CloseFile(string text, string Guid, string immeuble_id, string copro_id);
        
        [OperationContract(Action="http://tempuri.org/IService/CloseFile", ReplyAction="http://tempuri.org/IService/CloseFileResponse")]
        Task<string> CloseFileAsync(string text, string Guid, string immeuble_id, string copro_id);
        
        [OperationContract(Action="http://tempuri.org/IService/GetUserFromCode", ReplyAction="http://tempuri.org/IService/GetUserFromCodeResponse")]
        UserEntitie GetUserFromCode(string code);
        
        [OperationContract(Action="http://tempuri.org/IService/GetUserFromCode", ReplyAction="http://tempuri.org/IService/GetUserFromCodeResponse")]
        Task<UserEntitie> GetUserFromCodeAsync(string code);
        
        [OperationContract(Action="http://tempuri.org/IService/GetUserFromGuid", ReplyAction="http://tempuri.org/IService/GetUserFromGuidResponse")]
        UserEntitie GetUserFromGuid(string Guid);
        
        [OperationContract(Action="http://tempuri.org/IService/GetUserFromGuid", ReplyAction="http://tempuri.org/IService/GetUserFromGuidResponse")]
        Task<UserEntitie> GetUserFromGuidAsync(string Guid);
        
        [OperationContract(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        UserEntitie[] GetAllUsers();
        
        [OperationContract(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        Task<UserEntitie[]> GetAllUsersAsync();
        
        [OperationContract(Action="http://tempuri.org/IService/GetUserCoproprietaires", ReplyAction="http://tempuri.org/IService/GetUserCoproprietairesResponse")]
        ChildrenEntitie[] GetUserCoproprietaires(string guid);
        
        [OperationContract(Action="http://tempuri.org/IService/GetUserCoproprietaires", ReplyAction="http://tempuri.org/IService/GetUserCoproprietairesResponse")]
        Task<ChildrenEntitie[]> GetUserCoproprietairesAsync(string guid);
        
        [OperationContract(Action="http://tempuri.org/IService/GetCoproChildrens", ReplyAction="http://tempuri.org/IService/GetCoproChildrensResponse")]
        ChildrenEntitie[] GetCoproChildrens(string copro_id);
        
        [OperationContract(Action="http://tempuri.org/IService/GetCoproChildrens", ReplyAction="http://tempuri.org/IService/GetCoproChildrensResponse")]
        Task<ChildrenEntitie[]> GetCoproChildrensAsync(string copro_id);
        
        [OperationContract(Action="http://tempuri.org/IService/AddCopro", ReplyAction="http://tempuri.org/IService/AddCoproResponse")]
        string AddCopro(string user_id, string immeuble_id, string copro_id, string reference_imm, string adresse_imm, string reference_copro, string nom);
        
        [OperationContract(Action="http://tempuri.org/IService/AddCopro", ReplyAction="http://tempuri.org/IService/AddCoproResponse")]
        Task<string> AddCoproAsync(string user_id, string immeuble_id, string copro_id, string reference_imm, string adresse_imm, string reference_copro, string nom);
        
        [OperationContract(Action="http://tempuri.org/IService/DeleteUser", ReplyAction="http://tempuri.org/IService/DeleteUserResponse")]
        string DeleteUser(string guid);
        
        [OperationContract(Action="http://tempuri.org/IService/DeleteUser", ReplyAction="http://tempuri.org/IService/DeleteUserResponse")]
        Task<string> DeleteUserAsync(string guid);
        
        [OperationContract(Action="http://tempuri.org/IService/DeleteCopro", ReplyAction="http://tempuri.org/IService/DeleteCoproResponse")]
        string DeleteCopro(string guid);
        
        [OperationContract(Action="http://tempuri.org/IService/DeleteCopro", ReplyAction="http://tempuri.org/IService/DeleteCoproResponse")]
        Task<string> DeleteCoproAsync(string guid);
        
        [OperationContract(Action="http://tempuri.org/IService/GetListDocuments", ReplyAction="http://tempuri.org/IService/GetListDocumentsResponse")]
        DocumentEntitie[] GetListDocuments(string immeuble_id, string copro_id);
        
        [OperationContract(Action="http://tempuri.org/IService/GetListDocuments", ReplyAction="http://tempuri.org/IService/GetListDocumentsResponse")]
        Task<DocumentEntitie[]> GetListDocumentsAsync(string immeuble_id, string copro_id);
        
        [OperationContract(Action="http://tempuri.org/IService/DeleteDocument", ReplyAction="http://tempuri.org/IService/DeleteDocumentResponse")]
        string DeleteDocument(string guid);
        
        [OperationContract(Action="http://tempuri.org/IService/DeleteDocument", ReplyAction="http://tempuri.org/IService/DeleteDocumentResponse")]
        Task<string> DeleteDocumentAsync(string guid);
        
        [OperationContract(Action="http://tempuri.org/IService/Connected", ReplyAction="http://tempuri.org/IService/ConnectedResponse")]
        bool Connected();
        
        [OperationContract(Action="http://tempuri.org/IService/Connected", ReplyAction="http://tempuri.org/IService/ConnectedResponse")]
        Task<bool> ConnectedAsync();
        
        [OperationContract(Action="http://tempuri.org/IService/UpdateUser", ReplyAction="http://tempuri.org/IService/UpdateUserResponse")]
        string UpdateUser(string guid, string Code, string Password);
        
        [OperationContract(Action="http://tempuri.org/IService/UpdateUser", ReplyAction="http://tempuri.org/IService/UpdateUserResponse")]
        Task<string> UpdateUserAsync(string guid, string Code, string Password);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : IService, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : ClientBase<IService>, IService {
        
        private static Binding CreateBinding()
        {
            var binding = new BasicHttpBinding
            {
                MaxReceivedMessageSize = int.MaxValue,
                MaxBufferSize = int.MaxValue,
                MaxBufferPoolSize = int.MaxValue,
                OpenTimeout = TimeSpan.FromMinutes(10),
                CloseTimeout = TimeSpan.FromMinutes(10),
                SendTimeout = TimeSpan.FromMinutes(10),
                ReceiveTimeout = TimeSpan.FromMinutes(10),
                ReaderQuotas =
                {
                    MaxArrayLength = int.MaxValue,
                    MaxBytesPerRead = int.MaxValue,
                    MaxDepth = int.MaxValue,
                    MaxNameTableCharCount = int.MaxValue,
                    MaxStringContentLength = int.MaxValue
                }
            };

            return binding;
        }

        public ServiceClient()
            : this(new EndpointAddress("https://localhost:44373/Service.svc"))
        {
        }

        public ServiceClient(string serviceUrl)
            : this(new EndpointAddress(serviceUrl))
        {
        }

        public ServiceClient(EndpointAddress remoteAddress)
            : base(CreateBinding(), remoteAddress)
        {
        }

        public ServiceClient(Binding binding, EndpointAddress remoteAddress)
            : base(binding, remoteAddress)
        {
        }
        
        public string CreateUser(string Code, string Password) {
            return base.Channel.CreateUser(Code, Password);
        }
        
        public Task<string> CreateUserAsync(string Code, string Password) {
            return base.Channel.CreateUserAsync(Code, Password);
        }
        
        public void UploadPartFile(string Guid, byte[] filePart) {
            base.Channel.UploadPartFile(Guid, filePart);
        }
        
        public Task UploadPartFileAsync(string Guid, byte[] filePart) {
            return base.Channel.UploadPartFileAsync(Guid, filePart);
        }
        
        public string CloseFile(string text, string Guid, string immeuble_id, string copro_id) {
            return base.Channel.CloseFile(text, Guid, immeuble_id, copro_id);
        }
        
        public Task<string> CloseFileAsync(string text, string Guid, string immeuble_id, string copro_id) {
            return base.Channel.CloseFileAsync(text, Guid, immeuble_id, copro_id);
        }
        
        public UserEntitie GetUserFromCode(string code) {
            return base.Channel.GetUserFromCode(code);
        }
        
        public Task<UserEntitie> GetUserFromCodeAsync(string code) {
            return base.Channel.GetUserFromCodeAsync(code);
        }
        
        public UserEntitie GetUserFromGuid(string Guid) {
            return base.Channel.GetUserFromGuid(Guid);
        }
        
        public Task<UserEntitie> GetUserFromGuidAsync(string Guid) {
            return base.Channel.GetUserFromGuidAsync(Guid);
        }
        
        public UserEntitie[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public Task<UserEntitie[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public ChildrenEntitie[] GetUserCoproprietaires(string guid) {
            return base.Channel.GetUserCoproprietaires(guid);
        }
        
        public Task<ChildrenEntitie[]> GetUserCoproprietairesAsync(string guid) {
            return base.Channel.GetUserCoproprietairesAsync(guid);
        }
        
        public ChildrenEntitie[] GetCoproChildrens(string copro_id) {
            return base.Channel.GetCoproChildrens(copro_id);
        }
        
        public Task<ChildrenEntitie[]> GetCoproChildrensAsync(string copro_id) {
            return base.Channel.GetCoproChildrensAsync(copro_id);
        }
        
        public string AddCopro(string user_id, string immeuble_id, string copro_id, string reference_imm, string adresse_imm, string reference_copro, string nom) {
            return base.Channel.AddCopro(user_id, immeuble_id, copro_id, reference_imm, adresse_imm, reference_copro, nom);
        }
        
        public Task<string> AddCoproAsync(string user_id, string immeuble_id, string copro_id, string reference_imm, string adresse_imm, string reference_copro, string nom) {
            return base.Channel.AddCoproAsync(user_id, immeuble_id, copro_id, reference_imm, adresse_imm, reference_copro, nom);
        }
        
        public string DeleteUser(string guid) {
            return base.Channel.DeleteUser(guid);
        }
        
        public Task<string> DeleteUserAsync(string guid) {
            return base.Channel.DeleteUserAsync(guid);
        }
        
        public string DeleteCopro(string guid) {
            return base.Channel.DeleteCopro(guid);
        }
        
        public Task<string> DeleteCoproAsync(string guid) {
            return base.Channel.DeleteCoproAsync(guid);
        }
        
        public DocumentEntitie[] GetListDocuments(string immeuble_id, string copro_id) {
            return base.Channel.GetListDocuments(immeuble_id, copro_id);
        }
        
        public Task<DocumentEntitie[]> GetListDocumentsAsync(string immeuble_id, string copro_id) {
            return base.Channel.GetListDocumentsAsync(immeuble_id, copro_id);
        }
        
        public string DeleteDocument(string guid) {
            return base.Channel.DeleteDocument(guid);
        }
        
        public Task<string> DeleteDocumentAsync(string guid) {
            return base.Channel.DeleteDocumentAsync(guid);
        }
        
        public bool Connected() {
            return base.Channel.Connected();
        }
        
        public Task<bool> ConnectedAsync() {
            return base.Channel.ConnectedAsync();
        }
        
        public string UpdateUser(string guid, string Code, string Password) {
            return base.Channel.UpdateUser(guid, Code, Password);
        }
        
        public Task<string> UpdateUserAsync(string guid, string Code, string Password) {
            return base.Channel.UpdateUserAsync(guid, Code, Password);
        }
    }
}
