// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace SyndicDocumentsData.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migre1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migre1));
        
        string IMigrationMetadata.Id
        {
            get { return "201804260951399_Migre1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
