<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>

		<RootNamespace>EspaceSyndic</RootNamespace>
		<AssemblyName>SyndicApplication</AssemblyName>
		<StartupObject>EspaceSyndic.SyndicApplication</StartupObject>

		<ApplicationIcon>logo-ab2.ico</ApplicationIcon>

		<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>

		<Prefer32Bit>false</Prefer32Bit>
		<SignAssembly>false</SignAssembly>

		<AssemblyTitle>EspaceSyndic</AssemblyTitle>
		<Product>EspaceSyndic</Product>

		<Version>2.1.1</Version>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<FileVersion>$(Version)</FileVersion>
		<InformationalVersion>$(Version)</InformationalVersion>

		<Company>Atelier Logiciel Sandré</Company>
		<Product>Gestion de Copropriétés Agence Bourgogne</Product>
		<Authors>Enzo Sandré</Authors>

		<!--Required by RazorLight in GenerateurGrandLivre-->
		<PreserveCompilationContext>true</PreserveCompilationContext>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="logo-ab2.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<AdditionalFiles Remove="Properties\app.manifest" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\additif.dotx" />
	  <None Remove="Resources\convocation.dotx" />
	  <None Remove="Resources\etiquettes.dotx" />
	  <None Remove="Resources\relance1.dotx" />
	  <None Remove="Resources\relance3.dotx" />
	  <None Remove="Resources\relance4.dotx" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Impressions\Budget\TableauComptableAnnexe3.rdlc" />
	  <EmbeddedResource Include="Impressions\Additif\ImprimerAdditifReport.rdlc" />
	  <EmbeddedResource Include="Impressions\AppelDeFond\AppelDeFondDetailReport.rdlc" />
	  <EmbeddedResource Include="Impressions\AppelDeFond\AppelDeFondMasterReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Balances\BalanceReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Bilan\AutreOperationReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Bilan\CompteExploitationReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Bilan\CompteGestionGeneralReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Bilan\ImpressionBilanComptableMasterReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Bilan\ReleveGeneralOperationGestionReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Bilan\SituationTresorerieReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Convocations\ConvocationMasterReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Convocations\ConvocationModeleReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Convocations\ConvocationReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Convocations\ConvocationViergeReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Convocations\ConvocationWordReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Convocations\ConvocFeuillePresence.rdlc" />
	  <EmbeddedResource Include="Impressions\EtiquetteReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Facture\ListeFacturationDetailReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Facture\ListeFacturationMasterReport.rdlc" />
	  <EmbeddedResource Include="Impressions\FeuillePresence.rdlc" />
	  <EmbeddedResource Include="Impressions\Immeuble.rdlc" />
	  <EmbeddedResource Include="Impressions\Reglement\ListeReglementDetailReport.rdlc" />
	  <EmbeddedResource Include="Impressions\Reglement\ListeReglementMasterReport.rdlc" />
	  <EmbeddedResource Include="Impressions\ReleveFiscal\ReleveFiscalDetailReport.rdlc" />
	  <EmbeddedResource Include="Impressions\ReleveFiscal\ReleveFiscalMasterReport.rdlc" />
	  <EmbeddedResource Include="Impressions\RelevesComptes\ReleveCompteReport.rdlc" />
	  <EmbeddedResource Include="Impressions\RelevesIndividuels\ReleveIndivDetailReport.rdlc" />
	  <EmbeddedResource Include="Impressions\RelevesIndividuels\ReleveIndivMasterReport.rdlc" />
	  <EmbeddedResource Include="Impressions\RemiseDeCles\RemiseDeCleReport.rdlc" />
	  <EmbeddedResource Include="Impressions\RetardsPaiements\RetardPaiementReport.rdlc" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Npgsql" Version="10.0.3" />
		<PackageReference Include="System.Data.Odbc" Version="10.0.9" />
		<PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
		<PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
		<PackageReference Include="ReportViewerCore.WinForms" Version="15.1.33" />
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.6.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="5.6.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CommonProjectsPartners\CommonProjectsPartners.csproj" />
		<ProjectReference Include="..\GenerateurGrandLivre\GenerateurGrandLivre.csproj" />
		<ProjectReference Include="..\SyndicData\SyndicData.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\additif.dotx" />
	  <Resource Include="Resources\convocation.dotx" />
	  <Resource Include="Resources\etiquettes.dotx" />
	  <Resource Include="Resources\relance1.dotx" />
	  <Resource Include="Resources\relance3.dotx" />
	  <Resource Include="Resources\relance4.dotx" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>